title: ITGPG — IT Department | Government Polytechnic Gandhinagar
description: Official website of the Information Technology Department at Government Polytechnic Gandhinagar (ITGPG). Access study materials, faculty info, events, certificates, and placement records for IT diploma courses under GTU.
baseurl: "/it"
url: "https://itgpg.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Prevent redirects
exclude: 
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/

# Collections
collections:
  events:
    output: true
    permalink: /events/:name/
  faculty:
    output: true
  student-corner:
    output: true
  co-curricular:
    output: true
  accreditation:
    output: true
  newsletter:
    output: true




# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: /assets/images/gpg-logo.png
      lang: en_IN 